language: bash
dist: focal
env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8

addons:
  snaps:
    - name: snapcraft
      classic: true
    - name: http
    - name: lxd

script:
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - mkdir -p "$TRAVIS_BUILD_DIR/snaps-cache"
  - export PATH=/snap/bin:$PATH
  - sudo snapcraft --use-lxd
  - sudo cp *.snap "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"

after_failure:
  - sudo journalctl -u snapd
  - http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16
